### ISSUE TITLE
How to config the docker run command?

### ISSUE THREAD

**Issue by l1teng** [UoD-CVIP/ServerImageBuilder#3]
Hi, 

sorry for disturbing you.

I pulled your docker image from ```dockerhub.com```, via

```
docker pull uodcvip/matlab:r2020b
```

After that, the docker run command is,

```
docker run -d --name matlab uodcvip/matlab:r2020b
```

however, the container does not work, 

![image](https://user-images.githubusercontent.com/54158716/129839007-45b9cccf-e967-43a1-9b34-1a923d56cf80.png)

I am not familiar with this docker image and hope you can help me with the ```matlab:2020b``` image run command configuration. 

Looking forward to your reply.

Best regards,

Teng Li

**Comment by dijksterhuis** [comment]
@litun5315 these images are used with our in-house GPU servers which runs a customised JupyterHub dockerspawner back-end. The images aren't built to run from command line as they assume JupyterHub will spawn them.

Although you wouldn't be able to use our matlab image anyway because you won't have access to the university's matlab license.

**Comment by l1teng** [comment]
Got it. Thanks for your reply.

Best regards,
Teng Li
